### ISSUE TITLE
[ENHANCEMENT] Filename convention for `examples` files to test

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensorPkgSkeleton.jl#33]
I think right now we run all files that end in `.jl` in the `examples` folder, probably we should have a naming convention like `testexample_f.jl` to specify which ones should get run in the tests, since not all examples will be appropriate to run in tests, some may be setup files, etc.

**Comment by mtfishman** [comment]
A question in that case is if we should rename `examples/README.jl` to that naming convention, or treat `README.jl` as a special file that gets run anyway.

**Comment by lkdvos** [comment]
I guess the question is probably what the intention is: are we running the examples files to ensure that they are still working, or do we intend to put some things in examples that are actually meant to test some behavior?

**Comment by mtfishman** [comment]
> I guess the question is probably what the intention is: are we running the examples files to ensure that they are still working, or do we intend to put some things in examples that are actually meant to test some behavior?

I think both, I've found it is nice to use `@test` in example files anyway to demonstrate what the output should be without printing things. But I see your point, primarily it is meant to test examples don't get outdated (we often have that problem with ITensor examples...), so probably we should include all files by default (recursively in folders as well since it can be nice to organize examples into folders) and then have a syntax for ignoring ones that aren't appropriate to run in tests, like if they rely on some interactivity or take too long to run. So for example we could have a convention that examples with names of the form `notest_f.jl` don't get run, and also we can have a convention that code in certain folders are treated as "setup code" and also ignored, like #31.

**Comment by mtfishman** [comment]
Closed by #41.
